[package]
name = "trussed-totp-pc-tutorial"
version = "0.1.0"
authors = ["Nicolas Stalder <nicolas@solokeys.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chacha20 = { version = "0.6.0", features = ["rng"] }
clap = { version = "2.33.3", default-features = false }
data-encoding = "2.3.2"
delog = "0.1.0-alpha.3"
generic-array = "0.14.3"
littlefs2 = { git = "https://github.com/nickray/littlefs2", branch = "closures-instead-of-ub" }
log = "0.4.14"
postcard = "0.5.1"
rand_core = { version = "0.5.1", features = ["getrandom"] }
serde = { version = "1", default-features = false, features = ["derive"] }
simple_logger = "1.11.0"

# is this possible?
# trussed = { git = "ssh://git@github.com/nickray/solo-bee.git", branch = "main"}
trussed = { path = "../solo-bee/components/trussed", features = ["clients-1"] }

[patch.crates-io]
heapless = { git = "https://github.com/nickray/heapless", branch = "bytebuf-0.5.6" }
nisty = { git = "https://github.com/ycrypto/nisty", branch = "main" }
